<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MsSubDivisiItemSeeder extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('ms_sub_divisi_items')->insert([
            [
                'id' => 1,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'Ijin RT/RW Sampai Kecamatan',
                'jumlah' => 33716,
                'harga' => 250,
                'total_harga' => 8429000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 2,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'Izin HO ( Izin Gangguan )',
                'jumlah' => 33716,
                'harga' => 1000,
                'total_harga' => 33716000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 3,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'Piel Banjir',
                'jumlah' => 33716,
                'harga' => 100,
                'total_harga' => 3371600,
                'is_calculated_price' => false,
            ],
            [
                'id' => 4,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'Izin Pengeringan Lahan',
                'jumlah' => 33716,
                'harga' => 200,
                'total_harga' => 6743200,
                'is_calculated_price' => false,
            ],
            [
                'id' => 5,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'IPPT',
                'jumlah' => 33716,
                'harga' => 1000,
                'total_harga' => 33716000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 6,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'UKL / UPL',
                'jumlah' => 33716,
                'harga' => 500,
                'total_harga' => 16858000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 7,
                'sub_divisi_id' => 5,
                'satuan_id' => 2,
                'nama' => 'IJIN LOKASI',
                'jumlah' => 33716,
                'harga' => 2500,
                'total_harga' => 84290000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 8,
                'sub_divisi_id' => 6,
                'satuan_id' => 2,
                'nama' => 'Pertek - BPN',
                'jumlah' => 33716,
                'harga' => 250,
                'total_harga' => 8429000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 9,
                'sub_divisi_id' => 6,
                'satuan_id' => 2,
                'nama' => 'Pertek - Dinas Terkait',
                'jumlah' => 33716,
                'harga' => 500,
                'total_harga' => 16858000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 10,
                'sub_divisi_id' => 13,
                'satuan_id' => 7,
                'nama' => 'IMB - Rumah Type 36/72',
                'jumlah' => 128,
                'harga' => 2000000,
                'total_harga' => 265000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 11,
                'sub_divisi_id' => 13,
                'satuan_id' => 7,
                'nama' => 'IMB - Rumah Type 45/84',
                'jumlah' => 90,
                'harga' => 2800000,
                'total_harga' => 252000000,
                'is_calculated_price' => false,
            ],
            [
                'id' =>12,
                'sub_divisi_id' => 14,
                'satuan_id' => 19,
                'nama' => 'Perencanaan Gate Way',
                'jumlah' => 1,
                'harga' => 7000000,
                'total_harga' => 7000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 13,
                'sub_divisi_id' => 14,
                'satuan_id' => 2,
                'nama' => 'Perencanaan Jalan & Saluran',
                'jumlah' => 11243,
                'harga' => 300,
                'total_harga' => 3372923,
                'is_calculated_price' => false,
            ],
            [
                'id' => 14,
                'sub_divisi_id' => 14,
                'satuan_id' => 7,
                'nama' => 'Gambar Unit Rumah',
                'jumlah' => 2,
                'harga' => 7000000,
                'total_harga' => 14000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 15,
                'sub_divisi_id' => 14,
                'satuan_id' => 2,
                'nama' => 'Perencanaan Pasos & Pasum',
                'jumlah' => 2036,
                'harga' => 5000,
                'total_harga' => 10179616,
                'is_calculated_price' => false,
            ],
            [
                'id' => 16,
                'sub_divisi_id' => 15,
                'satuan_id' => 2,
                'nama' => 'Pembersihan lahan',
                'jumlah' => 33716,
                'harga' => 1000,
                'total_harga' => 33716000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 17,
                'sub_divisi_id' => 15,
                'satuan_id' => 2,
                'nama' => 'Cut & Fill - Pembentukan Kontur Lahan',
                'jumlah' => 36228,
                'harga' => 20000,
                'total_harga' => 724560000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 18,
                'sub_divisi_id' => 15,
                'satuan_id' => 2,
                'nama' => 'Pematangan Lahan',
                'jumlah' => 33716,
                'harga' => 6000,
                'total_harga' => 202296000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 19,
                'sub_divisi_id' => 15,
                'satuan_id' => 20,
                'nama' => 'Pagar Kawasan ( Tinggi 1,5 m )',
                'jumlah' => 817,
                'harga' => 360000,
                'total_harga' => 294120000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 20,
                'sub_divisi_id' => 15,
                'satuan_id' => 2,
                'nama' => 'Pembangunan Perkerasan Jalan',
                'jumlah' => 9942,
                'harga' => 185000,
                'total_harga' => 1839237533,
                'is_calculated_price' => false,
            ],
            [
                'id' => 21,
                'sub_divisi_id' => 15,
                'satuan_id' => 19,
                'nama' => 'Pembangunan Gerbang Utama',
                'jumlah' => 1,
                'harga' => 400000000,
                'total_harga' => 400000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 22,
                'sub_divisi_id' => 15,
                'satuan_id' => 20,
                'nama' => 'Saluran Drainase',
                'jumlah' => 2603,
                'harga' => 185000,
                'total_harga' => 481463388,
                'is_calculated_price' => false,
            ],
            [
                'id' => 23,
                'sub_divisi_id' => 16,
                'satuan_id' => 7,
                'nama' => 'Konstruksi Unit Rumah Type 36/72',
                'jumlah' => 128,
                'harga' => 86400000,
                'total_harga' => 11059200000,
                'is_calculated_price' => true,
            ],
            [
                'id' => 24,
                'sub_divisi_id' => 16,
                'satuan_id' => 7,
                'nama' => 'Konstruksi Unit Rumah Type 45/84',
                'jumlah' => 90,
                'harga' => 117000000,
                'total_harga' => 10530000000,
                'is_calculated_price' => true,
            ],
            [
                'id' => 25,
                'sub_divisi_id' => 18,
                'satuan_id' => 7,
                'nama' => 'Trafo & Jaringan Induk PLN',
                'jumlah' => 4,
                'harga' => 5000000,
                'total_harga' => 20000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 26,
                'sub_divisi_id' => 18,
                'satuan_id' => 7,
                'nama' => 'Penyambungan Listrik Rumah',
                'jumlah' => 218,
                'harga' => 2000000,
                'total_harga' => 436000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 27,
                'sub_divisi_id' => 18,
                'satuan_id' => 7,
                'nama' => 'Tiang & Lampu Penerangan Jalan',
                'jumlah' => 26,
                'harga' => 2500000,
                'total_harga' => 65062620,
                'is_calculated_price' => false,
            ],
            [
                'id' => 28,
                'sub_divisi_id' => 18,
                'satuan_id' => 7,
                'nama' => 'Air Bersih & Pompa Air',
                'jumlah' => 218,
                'harga' => 2200000,
                'total_harga' => 479600000,
                'is_calculated_price' => false,
            ],

            [
                'id' => 29,
                'sub_divisi_id' => 19,
                'satuan_id' => 20,
                'nama' => 'Penghijauan Jalan Utama',
                'jumlah' => 140,
                'harga' => 500000,
                'total_harga' => 70000000,
                'is_calculated_price' => false,
            ],
            [
                'id' => 30,
                'sub_divisi_id' => 19,
                'satuan_id' => 2,
                'nama' => 'Taman & Area Bermain',
                'jumlah' => 1337,
                'harga' => 200000,
                'total_harga' => 267306620,
                'is_calculated_price' => false,
            ],
            [
                'id' => 31,
                'sub_divisi_id' => 19,
                'satuan_id' => 19,
                'nama' => 'Lapangan Olah Raga ( Bola Voly )',
                'jumlah' => 253,
                'harga' => 120000,
                'total_harga' => 30406800,
                'is_calculated_price' => false,
            ],
            [
                'id' => 32,
                'sub_divisi_id' => 19,
                'satuan_id' => 19,
                'nama' => 'Tempat Sarana Ibadah',
                'jumlah' => 1,
                'harga' => 600000000,
                'total_harga' => 600000000,
                'is_calculated_price' => false,
            ],
        ]);
    }
}
